### ISSUE TITLE
encoding is an invalid keyword

### ISSUE THREAD

**Issue by shoraj** [Lyonk71/pandas-dedupe#12]
TypeError:"python setup.py egg_info"failed with error code 1

**Comment by Lyonk71** [comment]
@shoraj can you let me know what OS you're using, and what version of Python? Also, did you clone the repo and run setup.py, or did you try pip install pandas-dedupe?

**Comment by shoraj** [comment]
OS: Windows 10
Python Version; 2.7
I didn't clone the repo, I tried installing using "pip install
pandas-dedupe".


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
01/02/19,
9:51:56 AM

**Comment by Lyonk71** [comment]
For ease of installation & performance, I prefer use WSL when I'm on Windows. Here's a link on how to set that up:  [https://www.youtube.com/watch?v=8VtSJZTT1R0&t=82s](https://www.youtube.com/watch?v=8VtSJZTT1R0&t=82s). That said, everything can work on Windows with some tinkering.

Regarding Python 2.7, I'm not sure if any of the packages I use are incompatible. I should have time this weekend to create an environment and test an install.

**Comment by shoraj** [comment]
Thank you


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
01/09/19,
8:47:35 PM

**Comment by Lyonk71** [comment]
@shoraj I've had a chance to try installing with Windows & Ubuntu for version 2.7 - I'm getting the same error.

I tried updating setup tools, and trying a few installation methods, but without success. For the time being, I'll leave a description that this is supported for Python 3 only. If you find a workaround, let me know!
