### ISSUE TITLE
RuntimeWarning: invalid value encountered in true_divide/greater/less_equal

### ISSUE THREAD

**Issue by soliverc** [Lyonk71/pandas-dedupe#21]
This warning popped up after I pressed 'f' after training. 

The labelled file with cluster IDs and confidence scores seemed to generate fine. Are these errors anything to worry about? 

If it means anything, the final labels were a bit imbalanced: `10/10 positive, 18/10 negative`

```
:\Users\seanc\Anaconda3\lib\site-packages\rlr\lr.py:47: RuntimeWarning: invalid value encountered in true_divide
  scores = np.exp(scores + self.bias) / (1 + np.exp(scores + self.bias))
C:\Users\seanc\Anaconda3\lib\site-packages\rlr\crossvalidation.py:108: RuntimeWarning: invalid value encountered in greater
  true_dupes = int(numpy.sum(predictions[true_labels == 1] > 0.5))
C:\Users\seanc\Anaconda3\lib\site-packages\rlr\crossvalidation.py:112: RuntimeWarning: invalid value encountered in less_equal
  false_distinct = int(numpy.sum(predictions[true_labels == 1] <= 0.5))
WARNING:dedupe.backport:Dedupe does not currently support multiprocessing on Windows
```

**Comment by Lyonk71** [comment]
I went down a rabbit hole looking for the answer to this in the past. My understanding is that it's just Numpy letting you know that a null value is being processed in an array. I don't believe there will be an issue with the output, but the folks at Datamade who wrote Dedupe may be able to give you a more definitive answer.
