### ISSUE TITLE
Standardize parameter

### ISSUE THREAD

**Issue by Lyonk71** [Lyonk71/pandas-dedupe#23]
A parameter is needed to toggle dataset standardization prior to deduplication/linkage. A rough outline of the parameter looks like:

`pandas_dedupe.dedupe_dataframe(df, ['field_1', 'field_2', ... ], standardize=True)`

```python
if standardize == True:
    clean_punctuation()
elif standardize == False:
    pass
else:
    Raise('standardize parameter must be True or False')
```

**Comment by soliverc** [comment]
Perhaps you could temporarily standardize the data just for the matching, then return the results including canonicals in original format. Would that be possible?

**Comment by Lyonk71** [comment]
That's a cool idea- I think it would require holding the original in memory which could be expensive

Another option I've played with is completely removing standardization from pandas_dedupe, and just making a library for cleaning/preprocessing

**Comment by soliverc** [comment]
You're right it will be expensive for big data... I've realized there are more errors after standardizing. I'm working with Irish customer data, so we have a lot of names like `O'Hara` etc. which becomes `ohara` after deduping. The apostrophe in the name is being removed. Going by your mini regex tutorial you gave me, if I add `\'` to the list of regex characters I'm guessing that will allow me to keep apostrophes. 

Anyway an option to standardize would be awesome. I'm going to play around with this in the package I downloaded:

```python
if standardize == True:
    clean_punctuation()
elif standardize == False:
    pass
else:
    Raise('standardize parameter must be True or False')
```

**Comment by Lyonk71** [comment]
> The apostrophe in the name is being removed. Going by your mini regex tutorial you gave me, if I add `\'` to the list of regex characters I'm guessing that will allow me to keep apostrophes.
> 

That's correct. How did prototyping your prototyping work out?
