### ISSUE TITLE
Records Matching: TypeErrror: descriptor 'union' of 'set' object needs an argument

### ISSUE THREAD

**Issue by cif2cif** [Lyonk71/pandas-dedupe#25]
I get this error after training dedupe.

Full code:
#load dataframes
dfa = pd.read_csv('data/dataset1-febrl.csv')
dfb = pd.read_csv('data/dataset2-febrl.csv')
#initiate matching
df_final = pandas_dedupe.link_dataframes(dfa, dfb, [' given_name', ' surname',  ' street_number', ' address_1', ' address_2', ' suburb', ' postcode', ' state', ' date_of_birth',' soc_sec_id'])

Best,

---------------------------------------------------
------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-24e74e79e069> in <module>
      1 #initiate matching
----> 2 df_final = pandas_dedupe.link_dataframes(dfa, dfb, [' given_name', ' surname',  ' street_number', ' address_1', ' address_2', ' suburb', ' postcode', ' state', ' date_of_birth',' soc_sec_id'])

~/anaconda3/lib/python3.7/site-packages/pandas_dedupe/link_dataframes.py in link_dataframes(dfa, dfb, field_properties, config_name)
     85 
     86         dedupe.consoleLabel(linker)
---> 87         linker.train()
     88 
     89         # When finished, save our training away to disk

~/anaconda3/lib/python3.7/site-packages/dedupe/api.py in train(self, recall, index_predicates)
    689 
    690         self.predicates = self.active_learner.learn_predicates(
--> 691             recall, index_predicates)
    692         self.blocker = blocking.Blocker(self.predicates)
    693         self.blocker.resetIndices()

~/anaconda3/lib/python3.7/site-packages/dedupe/labeler.py in learn_predicates(self, recall, index_predicates)
    384         else:
    385             learned_preds = self.blocker.block_learner.learn(dupes,
--> 386                                                              recall=recall)
    387 
    388         return learned_preds

~/anaconda3/lib/python3.7/site-packages/dedupe/training.py in learn(self, matches, recall)
     35         dupe_cover.dominators(cost=comparison_count)
     36 
---> 37         coverable_dupes = set.union(*viewvalues(dupe_cover))
     38         uncoverable_dupes = [pair for i, pair in enumerate(matches)
     39                              if i not in coverable_dupes]

TypeError: descriptor 'union' of 'set' object needs an argument

**Comment by Lyonk71** [comment]
Sorry I didn't get to this -> there have been a number of updates to the library since. Feel free to send a new issue request if you're still having problems.
