### ISSUE TITLE
Supervised learning data preparation 

### ISSUE THREAD

**Issue by schpedee** [Lyonk71/pandas-dedupe#28]
When using a supervised learning approach. I don't have labels for distinct pairs. But I do have pairs for golden records. Is it okay to use random pairs that arent in golden records and label then as distinct?

**Comment by ieriii** [comment]
@schpedee, I would suggest you post the question on stacks overflow, including a small example and an explaination of what to you are trying to achieve. 

@Lyonk71 : Since it is not an issue about pandas-dedupe, I suggest to close this issue down.
