### ISSUE TITLE
PyPi version out of date

### ISSUE THREAD

**Issue by vtasca** [Lyonk71/pandas-dedupe#38]
Hi, just a quick heads-up that the PyPi version of this excellent library is out of date and does not contain the `gazetteer_dataframe` module.

This leads to the following error when attempting to import it:

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-51-8e1027440477> in <module>
----> 1 df_deduped= pandas_dedupe.gazetteer_dataframe(df_one, df_two, 'Name', canonicalize=True)

AttributeError: module 'pandas_dedupe' has no attribute 'gazetteer_dataframe'
```

**Comment by ieriii** [comment]
Thank you for flagging this, @vtasca. 
Pinging @Lyonk71

**Comment by Lyonk71** [comment]
Sorry for the late reply, it's been a busy month! @vtasca You're correct that PyPi and the GitHub repo are on different versions. I only push new versions of pandas-dedupe to PyPi when I've had a chance to test new features. When I've had a chance to do code review, but no testing, I merge new features to the GitHub repo. The aim is that advanced users have access to all new features via the GitHub repo, but that less advanced users aren't subject to untested/potentially buggy code.

If you'd like to install the GitHub version of the repo, Do the following:
1. Clone the repo
2. In your terminal, run `pip uninstall <package_name>` to remove the existing version of the package
3. Run `pip install <path_to_local_cloned_package>

You may need to upgrade Python's `setuptools` package for the above steps to work. You'll find that the above steps should work with most Python projects you come across on GitHub.
