### ISSUE TITLE
Is it possible to use the Category type at the moment?

### ISSUE THREAD

**Issue by alexis-evelyn** [Lyonk71/pandas-dedupe#39]

**Comment by ieriii** [comment]
Hi @alexis-evelyn, 
Two quick questions that can help me understand the issue better:

1. Can you please provide a short explanation of what you are trying to achieve and a minimal example of how you'd like the feature to work in pandas-dedupe?

2. Is the code snippet below relevant for what you are trying to achieve?

```
import pandas as pd
import pandas_dedupe

# Import data
df = pd.DataFrame({'class': ['Iris-setosa', 'Iris-setossa', 'Iris-versicolor', 'Iris-virginica', 'versicolor', 'iris-setosa', 'versicolor'], 'category':['cat1', 'cat1', 'cat2', 'cat3', 'cat3', 'cat2', 'cat1']})

# Dedupe dataframe
dd = pandas_dedupe.dedupe_dataframe(
    df, 
    field_properties = ['class', 'category'], 
    sample_size=1,
    canonicalize=['class']
    )
``` 

Thank you.

**Comment by alexis-evelyn** [comment]
So, basically, I wanted to treat the list of categories like an enum so that the category could be used to weigh in on whether or not the rest of the data is the same or not.

For example:
```csv
name, description, category
Bob, Loves icecream, ICECREAM
Cube, Toy cube, TOY
Bob, Loves icecream and cake, DESSERT
```

Both Bob entries would be similar in that they are named the same and both love icecream, but the ICECREAM and DESSERT categories would differentiate them as two non-duplicate entries. I was hoping for category support to speed up the deduper as then the categories are treated like enums and not some form of text.

I'm not trying to canonicalize the categories as I generated them and already have them set to what I wanted to be, I'm just trying to take a list of names which are split between "owner name" and "brand" and then be able to figure out which one's are just typos (or alternate spellings) and which ones are actually different.

An example of a typo like what I saw is "breado" when "bread" was meant to be the correct spelling. Something like an example of the alternate spelling is "ABC, LLC" vs "ABC, LLC Alphabet".

As it appears that I'm not able to stick in a Variable definition directly into pandas-dedupe, I'm considering the field_property format below.

Variable Definition
```python
[
    # ...
    {'field': 'category', 'type': 'Categorical', 'categories' : ['MEDICAL', 'FOOD']},
    # ...
]
````

Suggested Field Properties
```python
field_properties: List[Tuple] = [
  # ...
  ("category", "Categorical", ("categories", ["MEDICAL", "FOOD"])),
  # ...
]
```

**Comment by ieriii** [comment]
Gotcha! Thanks for that :)

This is not supported at the moment. To do so, we need to refactor how data types are parsed.
I'll think about a way to do it in line with how the library works. 

I'll submit a PR when ready.

**Comment by ieriii** [comment]
Hi @alexis-evelyn,
See [here](https://github.com/Lyonk71/pandas-dedupe/tree/categorical-data) for a version of pandas-dedupe with categorical data.   
For now, it is in a separate branch (categorical-data). You need to `git clone` to use/test it.

Example usage:
```
import pandas as pd
import pandas_dedupe

df = pd.DataFrame({'class': ['Iris-setosa', 'Iris-setossa', 'Iris-versicolor', 'Iris-virginica', 'versicolor', 'iris-setosa', 'versicolor'], 'my_categories':['cat1', 'cat1', 'cat2', 'cat3', 'cat3', 'cat2', 'cat1']})

dd = pandas_dedupe.dedupe_dataframe(
    df, 
    field_properties = ['class', ['my_categories', 'Categorical', ['cat1','cat2','cat3']]], 
    sample_size=1,
    canonicalize=['class']
    )

# field_properties = ['my_categories', 'Categorical', ['cat1','cat2','cat3']]
# Explanation:  
# my_categories is the variable in the pandas dataframe
# 'Categorical' is the type (note the capital C)
# ['cat1', 'cat2', 'cat3'] are the categories (note thte python list).
```
Please test it and tell me what you think. If all ok, we can make it a permanent feature.

Alternative implementation:   
Require users to list categories in a python dictionary `{categories : ['cat1',cat2','cat3']}` rather than a simple list.

**Comment by ieriii** [comment]
Close for lack of engagement.

**Comment by derChristopher** [comment]
Hi @ieriii 
Looks like I am 4 days late! I could test your version of pandas-dedupe with categorical data, because I have a similar usecase as @alexis-evelyn .  Unfortunately I get a github 404 if I want to access your link.

**Comment by ieriii** [comment]
Hi @derChristopher, 

it should be up again :)

**Comment by derChristopher** [comment]
Hi @ieriii ,

in my opinion it works like a charm. First I had some problems because the categories in the dataset were not all capitalized like the categories in the list, but I think that was a preprocessing issue. Thank you for your contribution!

**Comment by ieriii** [comment]
Thanks @derChristopher. 
I'll think about whether this is the best way to add this feature and then maybe create a PR.

I'll keep it in a separate branch for now.
