### ISSUE TITLE
Gazetteer_dataframe not available on pypi installation

### ISSUE THREAD

**Issue by ciprian-cgr** [Lyonk71/pandas-dedupe#41]
Hi folks, just wanted to ask if there is an issue with the gazetteer_dataframe function. I noticed it's not available on PyPI although the PR has been merged some time ago.

**Comment by Lyonk71** [comment]
Hey, that's an oversight on my end. Personal life has been a bit crazy this year. I'll plan to bump the PyPI version tonight.

Thanks for reaching out!

**Comment by ciprian-cgr** [comment]
That's great news, thank you!
