### ISSUE TITLE
Parameter recall_weight not working.

### ISSUE THREAD

**Issue by PMK1991** [Lyonk71/pandas-dedupe#48]
Facing an error while setting recall_weight :TypeError: dedupe_dataframe() got an unexpected keyword argument 'recall_weight'

**Comment by ieriii** [comment]
hi @PMK1991. Many thanks for this.
the `recall_weight` is deprecated and has been changed to `threshold` since version 1.3.1, where `threshold` is defined as follows:   
```
threshold : float, default 0.4
         Only put together records into clusters if the cophenetic similarity of the cluster 
         is greater than the threshold.
```

We will change the Readme file accordingly.
